micronaut:
  application:
    name: kodehouse
  server:
    port: 8086
datasources:
  default:
    url: jdbc:mysql://localhost:3306/kasadokodigo?createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    schema-generate: CREATE

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql : true
jpa.default.properties.hibernate.format_sql : true
